# Generated by Django 5.0 on 2023-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storylandapp", "0002_book_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
